### ISSUE TITLE
User can register a handle to identify themselves

### ISSUE THREAD

**Issue by mstrieleman** [mstrieleman/react-native-project#1]
# Motivation
A user needs to create a unique identifier to send and receive messages associated with their handle.

# Implementation 

1. User opens app
2. User is presented with a text input for choosing a handle
3. User submits handle to App
4. App sends handle to server
5. Server checks handle against database 
- If handle is taken respond with error 
- if handle is available proceed
6. Server inserts username into database
7. Server returns username to app with 'creation success'
8. App shows username creation success to user

# Research
[Expo - Emulator / React Native](https://expo.io/)
[React Native Docs](https://facebook.github.io/react-native/)
Mobile app to server communication

# Tasks
- [ ] Create a wireframe for choosing a handle text input, button, logo,
- [ ] Create a wireframe for username creation success
- [ ] Create a wireframe for username creation fail
- [ ] Create a flow chart for Implementation flow

# Client
- [ ] Get bare bones app running in expo / emulator 
- [ ] Create form for user to submit username
- [ ] Define function for posting usernames to server
- [ ] Register post function to fire upon button press 
- [ ] Create view for showing user that username is unavailable
- [ ] Create view for showing user that username creation was a success
- [ ] Style UI to be visually appealing

# Server
- [ ] Create server route for handling post requests of usernames
- [ ] Create check to see if username is already been created in the database
- [ ] If username is already taken, respond to user with error
- [ ] If username is available, insert username to database
- [ ] Have server respond to client that user creation was a success
